# Generated by Django 5.2 on 2025-04-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('image_url', models.URLField()),
                ('status', models.CharField(choices=[('maintenance', 'Maintenance'), ('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], max_length=100)),
            ],
            options={
                'verbose_name': 'app',
                'verbose_name_plural': 'apps',
                'ordering': ['name'],
            },
        ),
    ]
