# Generated by Django 5.2 on 2025-04-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmodel',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appmodel',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appmodel',
            name='status',
            field=models.CharField(choices=[('maintenance', 'Maintenance'), ('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], default='maintenance', max_length=100),
        ),
    ]
