# Generated by Django 5.2 on 2025-04-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_apps', '0002_alter_appmodel_image_url_alter_appmodel_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmodel',
            name='description',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
