# Generated by Django 5.2 on 2025-04-25 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_apps', '0003_appmodel_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appmodel',
            options={'ordering': ('status',), 'verbose_name': 'app', 'verbose_name_plural': 'apps'},
        ),
    ]
