# Generated by Django 5.2 on 2025-04-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churn_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurnModelTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.FileField(upload_to='datasets/')),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('trained_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
