# Generated by Django 5.2 on 2025-04-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churn_app', '0002_churnmodeltrainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='churnmodeltrainer',
            name='verdict',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
