# Generated by Django 5.2 on 2025-04-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churn_app', '0004_testingcustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestingCustomerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=100)),
                ('marital_status', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('dependents', models.IntegerField()),
                ('account_type', models.CharField(max_length=50)),
                ('account_age_months', models.IntegerField()),
                ('num_products', models.IntegerField()),
                ('avg_balance', models.FloatField()),
                ('is_dormant', models.BooleanField()),
                ('mobile_banking_active', models.BooleanField()),
                ('monthly_mobile_logins', models.IntegerField()),
                ('ussd_usage', models.BooleanField()),
                ('internet_banking_active', models.BooleanField()),
                ('atm_txns_per_month', models.IntegerField()),
                ('account_linkage_active', models.BooleanField()),
                ('monthly_deposits', models.FloatField()),
                ('monthly_withdrawals', models.FloatField()),
                ('monthly_transfers', models.FloatField()),
                ('loan_repayment_history', models.FloatField()),
                ('complaints_count', models.IntegerField()),
                ('days_since_last_complaint', models.IntegerField()),
                ('satisfaction_rating', models.FloatField()),
                ('has_rel_manager', models.BooleanField()),
                ('sector', models.CharField(max_length=50)),
                ('monthly_fees', models.FloatField()),
                ('churned', models.BooleanField(default=None)),
            ],
        ),
        migrations.RenameModel(
            old_name='TestingCustomer',
            new_name='TrainingCustomerData',
        ),
        migrations.DeleteModel(
            name='BankCustomer',
        ),
        migrations.AlterField(
            model_name='churnmodeltrainer',
            name='dataset',
            field=models.FileField(help_text='Upload your training dataset here.', upload_to='datasets/'),
        ),
    ]
