# Generated by Django 5.2 on 2025-04-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churn_app', '0005_testingcustomerdata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testingcustomerdata',
            name='churn_probability',
            field=models.FloatField(default=0.0),
        ),
    ]
