# Generated by Django 5.2 on 2025-04-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spool_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spool',
            name='procedure_parameters',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
