# Generated by Django 5.2 on 2025-04-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spool_app', '0002_spool_procedure_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spool',
            name='procedure_parameters',
            field=models.JSONField(blank=True, choices=[('int', 'Integer'), ('str', 'String'), ('datetime', 'Datetime'), ('float', 'Float')], null=True),
        ),
    ]
