# Generated by Django 5.2 on 2025-04-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spool_app', '0003_alter_spool_procedure_parameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spool',
            name='procedure_parameters',
        ),
        migrations.AddField(
            model_name='spool',
            name='procedure_parameter_1',
            field=models.JSONField(blank=True, choices=[('int', 'Integer'), ('str', 'String'), ('float', 'Float'), ('datetime', 'Datetime')], null=True),
        ),
        migrations.AddField(
            model_name='spool',
            name='procedure_parameter_2',
            field=models.JSONField(blank=True, choices=[('int', 'Integer'), ('str', 'String'), ('float', 'Float'), ('datetime', 'Datetime')], null=True),
        ),
    ]
