# Generated by Django 5.2 on 2025-04-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spool_app', '0004_remove_spool_procedure_parameters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spool',
            name='procedure_parameter_1',
            field=models.CharField(blank=True, choices=[('float', 'Float'), ('int', 'Integer'), ('str', 'String'), ('datetime', 'Datetime')], null=True),
        ),
        migrations.AlterField(
            model_name='spool',
            name='procedure_parameter_2',
            field=models.CharField(blank=True, choices=[('float', 'Float'), ('int', 'Integer'), ('str', 'String'), ('datetime', 'Datetime')], null=True),
        ),
    ]
