# Generated by Django 5.2 on 2025-04-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spool_app', '0005_alter_spool_procedure_parameter_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spool',
            options={'ordering': ['report_code']},
        ),
        migrations.AlterField(
            model_name='spool',
            name='procedure_parameter_1',
            field=models.CharField(blank=True, choices=[('str', 'String'), ('date', 'Date time'), ('float', 'Float'), ('int', 'Integer')], null=True),
        ),
        migrations.AlterField(
            model_name='spool',
            name='procedure_parameter_2',
            field=models.CharField(blank=True, choices=[('str', 'String'), ('date', 'Date time'), ('float', 'Float'), ('int', 'Integer')], null=True),
        ),
    ]
