# Generated by Django 5.2 on 2025-04-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spool_app', '0006_alter_spool_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spool',
            name='procedure_parameter_1',
            field=models.CharField(blank=True, choices=[('date', 'Date'), ('float', 'Float'), ('string', 'String'), ('int', 'Integer')], null=True),
        ),
        migrations.AlterField(
            model_name='spool',
            name='procedure_parameter_2',
            field=models.CharField(blank=True, choices=[('date', 'Date'), ('float', 'Float'), ('string', 'String'), ('int', 'Integer')], null=True),
        ),
    ]
