# Generated by Django 5.2 on 2025-04-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spool_app', '0011_alter_spool_procedure_parameter_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spool',
            name='procedure_parameter_1',
            field=models.CharField(blank=True, choices=[('integer', 'Integer'), ('date', 'Date'), ('text', 'Text'), ('float', 'Float')], null=True),
        ),
        migrations.AlterField(
            model_name='spool',
            name='procedure_parameter_2',
            field=models.CharField(blank=True, choices=[('integer', 'Integer'), ('date', 'Date'), ('text', 'Text'), ('float', 'Float')], null=True),
        ),
    ]
