# Generated by Django 5.2 on 2025-04-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spool_app', '0013_alter_spool_procedure_parameter_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spool',
            name='access_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spool',
            name='procedure_parameter_1',
            field=models.CharField(blank=True, choices=[('date', 'Date'), ('float', 'Float'), ('integer', 'Integer'), ('text', 'Text')], null=True),
        ),
        migrations.AlterField(
            model_name='spool',
            name='procedure_parameter_2',
            field=models.CharField(blank=True, choices=[('date', 'Date'), ('float', 'Float'), ('integer', 'Integer'), ('text', 'Text')], null=True),
        ),
    ]
