# Generated by Django 5.2 on 2025-04-24 10:29

import spool_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spool_app', '0014_spool_access_list_alter_spool_procedure_parameter_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spool',
            name='procedure_parameter_1',
            field=models.CharField(blank=True, choices=[('date', 'Date'), ('text', 'Text'), ('integer', 'Integer'), ('float', 'Float')], null=True),
        ),
        migrations.AlterField(
            model_name='spool',
            name='procedure_parameter_2',
            field=models.CharField(blank=True, choices=[('date', 'Date'), ('text', 'Text'), ('integer', 'Integer'), ('float', 'Float')], null=True),
        ),
        migrations.AlterField(
            model_name='spool',
            name='report_code',
            field=models.CharField(blank=True, default=spool_app.models.generate_report_code, max_length=10, null=True, unique=True),
        ),
    ]
